name: .NET Framework Unit Tests

# Workflow буде запускатися у випадку push на гілки feature/* та develop,
# а також при створенні pull request в develop.
on:
  push:
    branches:
      - 'feature/*'
      - develop
  pull_request:
    types: [opened, edited, reopened, synchronize, review_requested, submitted]
    branches:
      - develop
  workflow_dispatch: # Дозволить вам запускати тести вручну через сайт, якщо знадобиться

jobs:
  # Job перевірки код-ревью (для убунти, тільки для pull_reques)
  review-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Перевірка наявності схваленого код-рев’ю
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            const approved = reviews.some(review => review.state === 'APPROVED');
            if (!approved) {
              core.setFailed("Код-рев’ю не схвалено! Зверніться до ментора.");
            
  build-and-test:
    # Використовуємо Windows-сервер, так як .NET Framework 4.7.2 прив'язаний до Windows компонентів
    runs-on: windows-latest

    steps:
      # Крок 1: Завантаження коду з репозиторію (використовуємо актуальную v4)
      - name: Checkout code
        uses: actions/checkout@v4

      # Крок 2: Додаємо MSBuild до PATH, щоб зібрати проекти Net Framework
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Крок 3: Додаємо NuGet для завантаження пакетів (бібліотек)
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # Крок 4: Відновлення залежностей через NuGet
      - name: Restore NuGet packages
        run: nuget restore PostMachine.sln

      # Крок 5: Компіляція проєкту за допомогою MSBuild у режимі Release
      - name: Build Solution
        run: msbuild PostMachine.sln /p:Configuration=Release

      # Крок 6: Запуск модульних тестів за допомогою маски пошуку
      - name: Run unit tests
        run: dotnet test **\Release\*Tests.dll --no-build

  analysis:
    runs-on: windows-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Run CLOC
        shell: powershell
        run: |
          # Встановлюємо cloc через Chocolatey
          choco install cloc -y          
          # Рахуємо рядки
          cloc . --exclude-dir=packages,bin,obj,.git,.github,sonar --xml --out=cloc-report.xml

      # Зберігаємо створені артефакти у Гітхаб
      - name: Upload CLOC Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloc-code-metrics       # Назва архіву
          path: cloc-report.xml         # Шлях

      # Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Встановлюємо сканер як глобальний dotnet-інструмент
      - name: Install SonarScanner Tool
        run: dotnet tool install --global dotnet-sonarscanner

      # Виконуємо послідовність команд, як ЛР 2
      - name: SonarQube Begin Build End
        shell: powershell
        run: |
          dotnet sonarscanner begin /k:"TuringMachine" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          
          dotnet clean PostMachine.sln
          dotnet build PostMachine.sln --configuration Release --no-incremental
          
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
